-- Create Profiles table (safe if exists)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),
  score integer default 0,
  updated_at timestamp with time zone,
  constraint username_length check (char_length(username) >= 3)
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Create policies for Profiles (drop first to avoid error)
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create Questions table
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  difficulty text check (difficulty in ('Easy', 'Medium', 'Hard')),
  input_format text,
  output_format text,
  constraints text,
  examples jsonb, -- Array of {input, output, explanation}
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Questions
alter table public.questions enable row level security;

drop policy if exists "Questions are viewable by everyone." on questions;
create policy "Questions are viewable by everyone."
  on questions for select
  using ( true );

-- Create Submissions table
create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  question_id bigint references public.questions(id) not null,
  code text not null,
  language_id integer not null,
  status text not null, -- 'Accepted', 'Wrong Answer', etc.
  runtime float,
  memory float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Submissions
alter table public.submissions enable row level security;

drop policy if exists "Users can view their own submissions." on submissions;
create policy "Users can view their own submissions."
  on submissions for select
  using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own submissions." on submissions;
create policy "Users can insert their own submissions."
  on submissions for insert
  with check ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on signup
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
